export type BlogPost = {
  slug: string;
  title: string;
  excerpt: string;
  publishedDate: string; // human-readable, shown in the byline (e.g. "March 18, 2026")
  updatedDate: string; // human-readable, shown in the byline
  datePublishedISO: string; // ISO 8601 for Article schema + OpenGraph + sitemap
  dateModifiedISO: string; // ISO 8601 for Article schema + OpenGraph + sitemap
  metaTitle: string;
  metaDescription: string;
  relatedServices: string[];
  image: string; // featured image, unique per post
};

export const BLOG_POSTS: BlogPost[] = [
  {
    slug: 'lvp-vs-engineered-hardwood',
    title: 'Which One to Choose Between LVP vs Engineered Hardwood',
    excerpt:
      'LVP is cheaper, waterproof, and lower-maintenance; engineered hardwood is real wood that adds more resale value and can be refinished. A side-by-side comparison.',
    publishedDate: 'May 31, 2026',
    updatedDate: 'May 31, 2026',
    datePublishedISO: '2026-05-31',
    dateModifiedISO: '2026-05-31',
    metaTitle: 'Which One Is Better Between LVP vs Engineered Hardwood',
    metaDescription:
      'LVP vs engineered hardwood compared: water resistance, cost, resale value, refinishing, and lifespan. Which is better for kitchens, pets, and real-wood value.',
    relatedServices: ['vinyl-flooring-san-diego', 'hardwood-flooring-san-diego', 'laminate-flooring-san-diego'],
    image: '/img/projects/portfolio/zelo-project-18.webp',
  },
  {
    slug: 'types-of-hardwood-flooring',
    title: 'Types of Hardwood Flooring by Species, Finish, and Width',
    excerpt:
      'The main types of hardwood flooring explained: solid vs engineered, popular wood species and their hardness, prefinished vs site-finished, and plank widths and grades.',
    publishedDate: 'May 31, 2026',
    updatedDate: 'May 31, 2026',
    datePublishedISO: '2026-05-31',
    dateModifiedISO: '2026-05-31',
    metaTitle: 'Types of Hardwood Flooring Explained (2026 Guide)',
    metaDescription:
      'The types of hardwood flooring: solid vs engineered, oak, maple, hickory and walnut species, prefinished vs site-finished, and plank widths. How to choose for your home.',
    relatedServices: ['hardwood-flooring-san-diego', 'vinyl-flooring-san-diego', 'laminate-flooring-san-diego'],
    image: '/img/projects/portfolio/zelo-project-14.webp',
  },
  {
    slug: 'low-pile-vs-high-pile-carpet',
    title: 'Which One Is Right for You Between Low Pile vs High Pile Carpet',
    excerpt:
      'Low pile carpet is durable and easy to clean for high-traffic areas and pets; high pile is soft and cozy for bedrooms. Carpet pile types compared, room by room.',
    publishedDate: 'May 31, 2026',
    updatedDate: 'May 31, 2026',
    datePublishedISO: '2026-05-31',
    dateModifiedISO: '2026-05-31',
    metaTitle: 'Which One Is Better Between Low Pile vs High Pile Carpet',
    metaDescription:
      'Low pile vs high pile carpet compared: durability, comfort, cleaning, and pets. Plus the main types of carpet pile and which is best for each room.',
    relatedServices: ['carpet-flooring-san-diego', 'laminate-flooring-san-diego', 'vinyl-flooring-san-diego'],
    image: '/img/projects/portfolio/zelo-project-23.webp',
  },
  {
    slug: 'how-to-clean-luxury-vinyl-plank-flooring',
    title: 'How to Clean Luxury Vinyl Plank Flooring',
    excerpt:
      'How to clean and maintain LVP: routine sweeping and damp mopping, the right cleaners, what to avoid (steam mops, wax, harsh chemicals), and stain and scratch tips.',
    publishedDate: 'May 31, 2026',
    updatedDate: 'May 31, 2026',
    datePublishedISO: '2026-05-31',
    dateModifiedISO: '2026-05-31',
    metaTitle: 'How to Clean Luxury Vinyl Plank Flooring (LVP)',
    metaDescription:
      'How to clean luxury vinyl plank flooring: the best cleaners, why to avoid steam mops and wax, stain removal, scratch prevention, and a simple maintenance schedule.',
    relatedServices: ['vinyl-flooring-san-diego', 'laminate-flooring-san-diego', 'tile-flooring-san-diego'],
    image: '/img/projects/portfolio/zelo-project-03.webp',
  },
  {
    slug: 'tile-vs-vinyl-flooring',
    title: 'Which One to Choose Between Tile vs Vinyl Flooring',
    excerpt:
      'Porcelain tile is the most durable and adds the most value; vinyl plank is softer, warmer, and cheaper. Both are waterproof. A room-by-room comparison on cost and feel.',
    publishedDate: 'May 31, 2026',
    updatedDate: 'May 31, 2026',
    datePublishedISO: '2026-05-31',
    dateModifiedISO: '2026-05-31',
    metaTitle: 'Which One Is Better Between Tile vs Vinyl Flooring',
    metaDescription:
      'Tile vs vinyl plank flooring compared: durability, water resistance, comfort, cost, and installation. Which is better for bathrooms, kitchens, and whole-home installs.',
    relatedServices: ['tile-flooring-san-diego', 'vinyl-flooring-san-diego', 'hardwood-flooring-san-diego'],
    image: '/img/tile-porcelain.webp',
  },
  {
    slug: 'vinyl-vs-laminate-flooring',
    title: 'Which One to Choose Between Vinyl vs Laminate Flooring',
    excerpt:
      'Vinyl plank is waterproof and better for kitchens, baths, and pets; laminate is harder, more textured, and usually cheaper. A side-by-side comparison by room, cost, and durability.',
    publishedDate: 'May 31, 2026',
    updatedDate: 'May 31, 2026',
    datePublishedISO: '2026-05-31',
    dateModifiedISO: '2026-05-31',
    metaTitle: 'Which One Is Better Between Vinyl vs Laminate Flooring',
    metaDescription:
      'Vinyl plank vs laminate flooring compared. Water resistance, durability, feel, cost, and which is better for kitchens, pets, and budgets. A clear room-by-room verdict.',
    relatedServices: ['vinyl-flooring-san-diego', 'laminate-flooring-san-diego', 'hardwood-flooring-san-diego'],
    image: '/img/projects/portfolio/zelo-project-01.webp',
  },
  {
    slug: 'how-to-install-vinyl-plank-flooring',
    title: 'How to Install Vinyl Plank Flooring (Step by Step)',
    excerpt:
      'A step-by-step guide to installing click-lock vinyl plank flooring: subfloor prep, acclimation, layout direction, expansion gaps, common mistakes, and when to hire a pro.',
    publishedDate: 'May 31, 2026',
    updatedDate: 'May 31, 2026',
    datePublishedISO: '2026-05-31',
    dateModifiedISO: '2026-05-31',
    metaTitle: 'How to Install Vinyl Plank Flooring (Step by Step)',
    metaDescription:
      'How to install vinyl plank flooring step by step: subfloor prep, acclimation, layout direction, expansion gaps, the most common mistakes, and when to hire a pro.',
    relatedServices: ['vinyl-flooring-san-diego', 'laminate-flooring-san-diego', 'tile-flooring-san-diego'],
    image: '/img/projects/portfolio/zelo-project-20.webp',
  },
  {
    slug: 'best-flooring-for-san-diego-homes',
    title: 'Best Flooring for San Diego Homes',
    excerpt:
      'The best flooring for San Diego homes is rigid-core LVP or engineered hardwood, built for slab foundations and coastal humidity. Best picks by goal, area, room, and budget.',
    publishedDate: 'May 31, 2026',
    updatedDate: 'May 31, 2026',
    datePublishedISO: '2026-05-31',
    dateModifiedISO: '2026-05-31',
    metaTitle: 'Best Flooring for San Diego Homes (2026 Guide)',
    metaDescription:
      'The best flooring for San Diego homes is engineered hardwood and rigid-core LVP, built for slab foundations and coastal humidity. Best picks by goal, area, room, and budget.',
    relatedServices: ['vinyl-flooring-san-diego', 'hardwood-flooring-san-diego', 'tile-flooring-san-diego'],
    image: '/img/projects/portfolio/zelo-project-02.webp',
  },
  {
    slug: 'how-long-does-hardwood-refinishing-take',
    title: 'How Long Does Hardwood Floor Refinishing Take?',
    excerpt:
      'Hardwood floor refinishing takes 3 to 5 days of active work, plus cure time before furniture and rugs go back. A day-by-day timeline and the factors that change it.',
    publishedDate: 'May 30, 2026',
    updatedDate: 'May 30, 2026',
    datePublishedISO: '2026-05-30',
    dateModifiedISO: '2026-05-30',
    metaTitle: 'How Long Does Hardwood Floor Refinishing Take?',
    metaDescription:
      'Hardwood floor refinishing takes 3 to 5 days of active work, plus cure time. Day-by-day timeline, water vs oil finish, and when you can walk, move furniture, and add rugs.',
    relatedServices: ['hardwood-flooring-san-diego', 'laminate-flooring-san-diego', 'vinyl-flooring-san-diego'],
    image: '/img/projects/portfolio/zelo-project-04.webp',
  },
  {
    slug: 'laminate-flooring-thickness',
    title: 'Laminate Flooring Thickness and Wear Layers Explained',
    excerpt:
      'Laminate ranges from 6mm to 12mm thick. Here is what thickness actually affects, how it differs from the AC wear rating, and which combination to choose by room.',
    publishedDate: 'May 30, 2026',
    updatedDate: 'June 2, 2026',
    datePublishedISO: '2026-05-30',
    dateModifiedISO: '2026-06-02',
    metaTitle: 'Laminate Flooring Thickness From 7mm to 12mm Explained',
    metaDescription:
      'Laminate flooring ranges from 6mm to 12mm thick. What thickness actually affects, how it differs from the AC wear rating, and which to choose by room.',
    relatedServices: ['laminate-flooring-san-diego', 'vinyl-flooring-san-diego', 'hardwood-flooring-san-diego'],
    image: '/img/laminate-ac5-rating.webp',
  },
  {
    slug: 'laminate-over-existing-floors',
    title: 'Can You Install Laminate Over Existing Floors?',
    excerpt:
      'Yes, in most cases, if the surface is flat, solid, and dry. A surface-by-surface guide to installing laminate over tile, vinyl, hardwood, concrete, existing laminate, and carpet.',
    publishedDate: 'May 30, 2026',
    updatedDate: 'June 2, 2026',
    datePublishedISO: '2026-05-30',
    dateModifiedISO: '2026-06-02',
    metaTitle: 'Can You Install Laminate Over Existing Floors?',
    metaDescription:
      'Yes, laminate can go over tile, vinyl, hardwood, and concrete if the floor is flat, solid, and dry. Surface-by-surface guide to floating laminate over existing floors.',
    relatedServices: ['laminate-flooring-san-diego', 'tile-flooring-san-diego', 'vinyl-flooring-san-diego'],
    image: '/img/projects/portfolio/zelo-project-12.webp',
  },
  {
    slug: 'cost-to-install-carpet',
    title: 'How Much Carpet Installation Costs in 2026',
    excerpt: 'How much does it cost to install carpet? National average is $3-$8/sqft installed. We break down carpet installation costs by carpet type, room size, labor, and what is included in a professional estimate.',
    publishedDate: 'March 18, 2026',
    updatedDate: 'May 6, 2026',
    datePublishedISO: '2026-03-18',
    dateModifiedISO: '2026-05-06',
    image: '/img/projects/portfolio/zelo-project-16.webp',
    metaTitle: 'Carpet Installation Cost in 2026 - $3-$8/sqft Installed Guide',
    metaDescription: 'Carpet installation costs $3-$8 per square foot installed in 2026. Full breakdown by fiber, brand, pad, room size, stair cost, labor cost per square foot, and what should be included in your quote.',
    relatedServices: ['carpet-flooring-san-diego', 'vinyl-flooring-san-diego', 'laminate-flooring-san-diego'],
  },
  {
    slug: 'best-carpet-for-living-room',
    title: 'Choosing the Right Carpet for a Living Room',
    excerpt: 'Choosing carpet for your living room means balancing comfort, durability, and stain resistance. Here is what actually works based on years of installing carpet in San Diego homes.',
    publishedDate: 'February 28, 2026',
    updatedDate: 'May 6, 2026',
    datePublishedISO: '2026-02-28',
    dateModifiedISO: '2026-05-06',
    image: '/img/Patterned-Carpet.webp',
    metaTitle: 'Best Carpet for Living Room - 2026 Buyer Guide',
    metaDescription: 'Choosing the best carpet for a living room in 2026. Fiber, face weight, density, pile type, brand, color trend, and allergy-friendly options compared by San Diego carpet installers.',
    relatedServices: ['carpet-flooring-san-diego'],
  },
  {
    slug: 'lvp-vs-hardwood',
    title: 'LVP vs Hardwood Flooring in 2026',
    excerpt: 'Comparing luxury vinyl plank and hardwood flooring on cost, durability, water resistance, and long-term value.',
    publishedDate: 'February 10, 2026',
    updatedDate: 'May 6, 2026',
    datePublishedISO: '2026-02-10',
    dateModifiedISO: '2026-05-06',
    image: '/img/vinyl-plank-light-oak.webp',
    metaTitle: 'LVP vs Hardwood Flooring - 2026 Buyer Guide',
    metaDescription: 'LVP vs hardwood flooring comparison. Cost, durability, water resistance, and which works better for your home. Expert breakdown from licensed installers.',
    relatedServices: ['vinyl-flooring-san-diego', 'hardwood-flooring-san-diego'],
  },
  {
    slug: 'best-flooring-for-pets',
    title: 'The Best Flooring for Homes with Pets',
    excerpt: 'Scratch-resistant, waterproof, and easy to clean. Here are the flooring types that hold up best with dogs and cats.',
    publishedDate: 'January 22, 2026',
    updatedDate: 'May 6, 2026',
    datePublishedISO: '2026-01-22',
    dateModifiedISO: '2026-05-06',
    image: '/img/projects/portfolio/zelo-project-08.webp',
    metaTitle: 'Best Flooring For Homes With Pets - 2026 Buyer Guide',
    metaDescription: 'Best flooring for homes with pets. Scratch-proof, waterproof options compared. LVP, tile, laminate, and carpet rated for dogs and cats.',
    relatedServices: ['vinyl-flooring-san-diego', 'tile-flooring-san-diego', 'carpet-flooring-san-diego'],
  },
  {
    slug: 'vinyl-plank-flooring-cost',
    title: 'How Much Vinyl Plank Flooring Costs in 2026',
    excerpt: 'How much does vinyl plank flooring cost to install? We break down LVP costs by product type, room size, and labor.',
    publishedDate: 'January 8, 2026',
    updatedDate: 'May 6, 2026',
    datePublishedISO: '2026-01-08',
    dateModifiedISO: '2026-05-06',
    image: '/img/Luxury-Vinyl-Plank.jpg',
    metaTitle: 'Vinyl Plank Flooring Cost in 2026 - $4-$16/sqft Installed',
    metaDescription: 'Vinyl plank flooring installation cost in 2026. Average $4-$9 per square foot installed. Breakdown by LVP type, room size, labor, and what affects price.',
    relatedServices: ['vinyl-flooring-san-diego'],
  },
  {
    slug: 'polyester-vs-nylon-carpet',
    title: 'Which Fiber Is Better for Your Home Between Polyester vs Nylon Carpet',
    excerpt: 'Nylon is more durable. Polyester is cheaper. But the right choice depends on your room, traffic, and budget.',
    publishedDate: 'December 18, 2025',
    updatedDate: 'May 6, 2026',
    datePublishedISO: '2025-12-18',
    dateModifiedISO: '2026-05-06',
    image: '/img/projects/portfolio/zelo-project-11.webp',
    metaTitle: 'Polyester vs Nylon Carpet - 2026 Fiber Buyer Guide',
    metaDescription: 'Polyester vs nylon carpet compared in 2026. Durability, stain resistance, real-life pet and stain handling, cost tiers, and brand picks for every room and traffic level.',
    relatedServices: ['carpet-flooring-san-diego'],
  },
  {
    slug: 'engineered-vs-solid-hardwood',
    title: 'Which One to Install Between Engineered Hardwood vs Solid Hardwood',
    excerpt: 'Engineered hardwood handles moisture and concrete slabs better. Solid hardwood can be refinished more times. Here is how to choose.',
    publishedDate: 'December 5, 2025',
    updatedDate: 'May 6, 2026',
    datePublishedISO: '2025-12-05',
    dateModifiedISO: '2026-05-06',
    image: '/img/projects/portfolio/zelo-project-07.webp',
    metaTitle: 'Engineered vs Solid Hardwood - 2026 Buyer Guide',
    metaDescription: 'Engineered vs solid hardwood compared in 2026. Wear layer thickness, refinishing potential, install method by subfloor, cost tiers, brand picks, and which works in your home.',
    relatedServices: ['hardwood-flooring-san-diego'],
  },
  {
    slug: 'flooring-services-guide',
    title: "Flooring Services Guide - What's Included and What It Costs",
    excerpt: "Flooring services cover measurement, subfloor prep, removal, installation, and cleanup. Here's what each of our 8 flooring types costs installed in 2026, how long each takes, and what a trustworthy quote should include.",
    publishedDate: 'July 9, 2026',
    updatedDate: 'July 9, 2026',
    datePublishedISO: '2026-07-09',
    dateModifiedISO: '2026-07-09',
    image: '/img/projects/portfolio/zelo-project-05.webp',
    metaTitle: "Flooring Services Guide - Cost and What's Included",
    metaDescription: "Flooring services explained: what's included, 2026 cost by type ($2-$15/sqft), install timelines, and how to read a quote. CSLB-licensed San Diego installers.",
    relatedServices: [
      'carpet-flooring-san-diego',
      'vinyl-flooring-san-diego',
      'hardwood-flooring-san-diego',
      'laminate-flooring-san-diego',
      'tile-flooring-san-diego',
      'cork-flooring-san-diego',
      'rubber-flooring-san-diego',
      'vinyl-composition-tile-flooring-san-diego',
    ],
  },
  {
    slug: 'how-to-choose-a-flooring-company',
    title: 'How to Choose a Flooring Installation Company',
    excerpt: 'The safest way to choose a flooring installation company is to verify the CSLB license, read reviews for pattern not star count, and compare a written itemized estimate against at least one other bid before you sign anything.',
    publishedDate: 'July 10, 2026',
    updatedDate: 'July 10, 2026',
    datePublishedISO: '2026-07-10',
    dateModifiedISO: '2026-07-10',
    image: '/img/projects/portfolio/zelo-project-06.webp',
    metaTitle: 'How to Choose a Flooring Installation Company',
    metaDescription: 'How to choose a flooring installation company in 2026: verify the CSLB license, spot red flags, and compare estimates. A licensed San Diego installer\'s guide.',
    relatedServices: [
      'carpet-flooring-san-diego',
      'vinyl-flooring-san-diego',
      'hardwood-flooring-san-diego',
      'laminate-flooring-san-diego',
      'tile-flooring-san-diego',
      'cork-flooring-san-diego',
      'rubber-flooring-san-diego',
      'vinyl-composition-tile-flooring-san-diego',
    ],
  },
  {
    slug: 'is-free-flooring-installation-real',
    title: 'Is Free Flooring Installation Really Free?',
    excerpt: "Free flooring installation almost always means the labor cost gets folded into a higher material price rather than waived. Here's how to spot the difference and compare quotes fairly.",
    publishedDate: 'July 11, 2026',
    updatedDate: 'July 11, 2026',
    datePublishedISO: '2026-07-11',
    dateModifiedISO: '2026-07-11',
    image: '/img/projects/portfolio/zelo-project-09.webp',
    metaTitle: 'Is Free Flooring Installation Really Free?',
    metaDescription: "Is free flooring installation really free? See how the cost gets built into pricing, what's usually left out, and how to compare quotes fairly.",
    relatedServices: ['carpet-flooring-san-diego', 'vinyl-flooring-san-diego', 'laminate-flooring-san-diego'],
  },
  {
    slug: 'wall-to-wall-carpet',
    title: 'What Is Wall-to-Wall Carpet? Pros, Cons, and Cost',
    excerpt: "Wall-to-wall carpet is stretched over padding and tacked at the perimeter to cover an entire room, unlike a loose area rug. Here is what it costs installed in 2026, where it makes sense, and where it doesn't.",
    publishedDate: 'July 12, 2026',
    updatedDate: 'July 12, 2026',
    datePublishedISO: '2026-07-12',
    dateModifiedISO: '2026-07-12',
    image: '/img/carpet_all-1.webp',
    metaTitle: 'What Is Wall-to-Wall Carpet? Cost, Pros, and Cons',
    metaDescription: "What is wall-to-wall carpet? Installed cost, pros and cons, best rooms, and how it compares to area rugs, carpet tile, and hard flooring in 2026.",
    relatedServices: ['carpet-flooring-san-diego', 'laminate-flooring-san-diego', 'vinyl-flooring-san-diego'],
  },
  {
    slug: 'flooring-design-ideas-by-room',
    title: 'Flooring Design Ideas by Room and Style',
    excerpt: 'Flooring design starts with matching material to room: wood-look tile in entryways, wide-plank hardwood in living rooms, herringbone-pattern LVP in kitchens. A room-by-room guide to what we recommend and the trends shaping 2026.',
    publishedDate: 'July 13, 2026',
    updatedDate: 'July 13, 2026',
    datePublishedISO: '2026-07-13',
    dateModifiedISO: '2026-07-13',
    image: '/img/projects/portfolio/zelo-project-10.webp',
    metaTitle: 'Flooring Design Ideas by Room (2026 Guide)',
    metaDescription: 'Flooring design ideas for every room, entryway to home office, plus the wide-plank, matte-finish, and herringbone trends shaping 2026 flooring design.',
    relatedServices: ['vinyl-flooring-san-diego', 'tile-flooring-san-diego', 'hardwood-flooring-san-diego', 'laminate-flooring-san-diego'],
  },
  {
    slug: 'wood-look-tile-vs-hardwood',
    title: 'Wood Look Tile vs Real Hardwood Flooring, How to Tell Them Apart',
    excerpt: 'Wood look tile is waterproof porcelain built to mimic hardwood, the better pick for bathrooms and coastal homes. Real hardwood still wins on feel underfoot and resale value in dry, low-traffic rooms.',
    publishedDate: 'July 14, 2026',
    updatedDate: 'July 14, 2026',
    datePublishedISO: '2026-07-14',
    dateModifiedISO: '2026-07-14',
    image: '/img/tile-ceramic.webp',
    metaTitle: 'Wood Look Tile vs Hardwood Flooring Compared',
    metaDescription: "Wood look tile vs real hardwood flooring compared: water resistance, cost, feel underfoot, and how to tell them apart. Which is better for San Diego's coast.",
    relatedServices: ['tile-flooring-san-diego', 'hardwood-flooring-san-diego', 'vinyl-flooring-san-diego'],
  },
  {
    slug: 'bathroom-flooring-installation',
    title: 'What to Expect from Professional Bathroom Flooring Installation',
    excerpt: "Professional bathroom flooring installation means more than laying tile or vinyl, it requires waterproofing, subfloor prep, and drain slope. Here's what a proper install involves, what it costs, and why hardwood doesn't belong in a full bathroom.",
    publishedDate: 'July 15, 2026',
    updatedDate: 'July 15, 2026',
    datePublishedISO: '2026-07-15',
    dateModifiedISO: '2026-07-15',
    image: '/img/Tile-Flooring-toilet.webp',
    metaTitle: 'Professional Bathroom Flooring Installation Guide',
    metaDescription: "Professional bathroom flooring installation cost, timeline, and waterproofing methods explained. Tile vs LVP compared, plus why hardwood isn't recommended.",
    relatedServices: ['tile-flooring-san-diego', 'vinyl-flooring-san-diego', 'hardwood-flooring-san-diego'],
  },
  {
    slug: 'best-flooring-for-new-construction',
    title: 'Best Flooring for New Construction Homes',
    excerpt: "The best flooring for new construction homes is rigid-core LVP for whole-home durability, engineered hardwood for main living areas, and water-resistant laminate for budget upgrades. New construction adds one problem a renovation doesn't have: a curing concrete slab still releasing moisture.",
    publishedDate: 'July 16, 2026',
    updatedDate: 'July 16, 2026',
    datePublishedISO: '2026-07-16',
    dateModifiedISO: '2026-07-16',
    image: '/img/projects/portfolio/zelo-project-13.webp',
    metaTitle: 'Best Flooring for New Construction Homes (2026)',
    metaDescription: 'Best flooring for new construction homes: rigid-core LVP, engineered hardwood, and laminate compared. Slab drying time, builder-grade upgrades, and cost.',
    relatedServices: ['vinyl-flooring-san-diego', 'hardwood-flooring-san-diego', 'laminate-flooring-san-diego'],
  },
  {
    slug: 'best-flooring-for-schools',
    title: 'Best Flooring for Schools and Educational Facilities',
    excerpt: 'VCT is the standard for classrooms, hallways, and cafeterias; rubber takes over in gyms and multipurpose rooms. A cost and maintenance breakdown for facilities managers planning school flooring.',
    publishedDate: 'July 17, 2026',
    updatedDate: 'July 17, 2026',
    datePublishedISO: '2026-07-17',
    dateModifiedISO: '2026-07-17',
    image: '/img/vct-commercial-space.webp',
    metaTitle: 'Best Flooring for Schools and Educational Facilities',
    metaDescription: 'Flooring installation for schools compared: VCT vs rubber by room, real cost per sqft, strip-and-wax maintenance cycles, and ADA transition rules.',
    relatedServices: ['vinyl-composition-tile-flooring-san-diego', 'rubber-flooring-san-diego', 'tile-flooring-san-diego'],
  },
  {
    slug: 'best-flooring-for-craft-room',
    title: 'Best Flooring for a Craft Room or Home Office',
    excerpt: 'Cork is the best flooring for a craft room or home office: it cushions long standing sessions, absorbs sound for calls, and resists spills with a sealed finish. Laminate is the budget pick; vinyl plank is safest for heavy paint or resin work.',
    publishedDate: 'July 18, 2026',
    updatedDate: 'July 18, 2026',
    datePublishedISO: '2026-07-18',
    dateModifiedISO: '2026-07-18',
    image: '/img/cork-natural-finish.webp',
    metaTitle: 'Best Flooring for a Craft Room or Home Office',
    metaDescription: 'Best flooring for a craft room or home office: cork for comfort and sound, laminate for budget, vinyl plank for spill resistance. Costs and FAQs inside.',
    relatedServices: ['cork-flooring-san-diego', 'laminate-flooring-san-diego', 'vinyl-flooring-san-diego'],
  },
  {
    slug: 'bathroom-floor-tile-ideas',
    title: 'Bathroom Floor Tile Ideas by Style, Size, and Budget',
    excerpt: 'The best bathroom floor tile ideas by budget are large-format porcelain, wood-look plank, and mosaic or pebble tile in the shower pan. A guide to size, finish, and layout that also make small bathrooms look bigger.',
    publishedDate: 'July 19, 2026',
    updatedDate: 'July 19, 2026',
    datePublishedISO: '2026-07-19',
    dateModifiedISO: '2026-07-19',
    metaTitle: 'Bathroom Floor Tile Ideas by Style, Size, and Budget',
    metaDescription: 'Bathroom floor tile ideas by budget tier, from large-format porcelain to wood-look plank and mosaic shower tile. Costs per square foot, matte vs glossy finish, and small-bathroom layout tips.',
    relatedServices: ['tile-flooring-san-diego', 'hardwood-flooring-san-diego'],
    image: '/img/Porcelain-Tile-1.jpg',
  },
  {
    slug: 'best-tile-for-outdoor-patios-and-pools',
    title: 'Best Tile for Outdoor Patios and Pool Decks',
    excerpt: 'The best tile for patios and pool decks is through-body porcelain rated for exterior use, with low water absorption and a wet slip rating of at least 0.60. A guide to frost rating, slip resistance, and expansion joints.',
    publishedDate: 'July 20, 2026',
    updatedDate: 'July 20, 2026',
    datePublishedISO: '2026-07-20',
    dateModifiedISO: '2026-07-20',
    metaTitle: 'Best Tile for Outdoor Patios and Pool Decks (2026)',
    metaDescription: 'Best tile for outdoor patios and pool decks: porcelain vs travertine, DCOF slip rating, frost resistance, and expansion joint spacing. Installed costs for San Diego patio and pool tile projects.',
    relatedServices: ['tile-flooring-san-diego', 'vinyl-flooring-san-diego'],
    image: '/img/Natural-Stone-Tile.jpg',
  },
  {
    slug: 'can-laminate-flooring-be-repaired',
    title: 'Can Laminate Flooring Be Repaired?',
    excerpt: 'Yes, laminate flooring can be repaired in most cases, depending on how the damage happened. A single scratched plank swaps out in an afternoon, but water damage at the seams usually means replacement, not drying.',
    publishedDate: 'July 21, 2026',
    updatedDate: 'July 21, 2026',
    datePublishedISO: '2026-07-21',
    dateModifiedISO: '2026-07-21',
    metaTitle: 'Can Laminate Flooring Be Repaired?',
    metaDescription: 'Can laminate flooring be repaired? Plank replacement, scratch and water damage fixes, and real repair-vs-replace costs for laminate floors, from a single plank swap to a full room.',
    relatedServices: ['laminate-flooring-san-diego', 'vinyl-flooring-san-diego', 'tile-flooring-san-diego'],
    image: '/img/laminate-room-install.webp',
  },
  {
    slug: 'carpet-padding-guide',
    title: 'Carpet Padding Guide, Thickness and Density Explained',
    excerpt: 'Carpet padding is rated by thickness and density, and thicker is not always better. An 8 lb density rebond pad at 7/16 inch is the residential standard, and the wrong pad can void your carpet\'s warranty.',
    publishedDate: 'July 22, 2026',
    updatedDate: 'July 22, 2026',
    datePublishedISO: '2026-07-22',
    dateModifiedISO: '2026-07-22',
    metaTitle: 'Carpet Padding Guide, Thickness vs Density',
    metaDescription: 'Carpet padding guide covering thickness vs density, the 8 lb rebond standard, moisture-barrier pads for pets, and how the wrong pad choice can void a carpet manufacturer warranty.',
    relatedServices: ['carpet-flooring-san-diego', 'vinyl-flooring-san-diego'],
    image: '/img/Textured-Carpet.webp',
  },
  {
    slug: 'cork-flooring-maintenance-and-cleaning',
    title: 'Cork Flooring Maintenance and Cleaning Guide',
    excerpt: 'Cork flooring needs less upkeep than hardwood. Sweep or vacuum a few times a week, damp mop, keep it out of direct sun, and reseal the finish every 3 to 5 years to make a cork floor last 25 to 40 years.',
    publishedDate: 'July 23, 2026',
    updatedDate: 'July 23, 2026',
    datePublishedISO: '2026-07-23',
    dateModifiedISO: '2026-07-23',
    metaTitle: 'Cork Flooring Maintenance and Cleaning Guide',
    metaDescription: 'Cork flooring maintenance and cleaning guide covering routine cleaning, resealing schedule, UV fading prevention, and pet-proofing for cork floors that last 25 to 40 years.',
    relatedServices: ['cork-flooring-san-diego', 'hardwood-flooring-san-diego', 'laminate-flooring-san-diego'],
    image: '/img/Cork-naturally-resists-mold.webp',
  },
  {
    slug: 'flooring-for-rental-properties',
    title: 'Best Flooring for Rental Properties',
    excerpt: 'Rigid-core LVP is the best all-around flooring for rental units, holding up to tenant turnover and moisture at $4.50 to $7.50 per square foot. A cost and turn-time comparison of LVP, laminate, carpet, and VCT.',
    publishedDate: 'July 24, 2026',
    updatedDate: 'July 24, 2026',
    datePublishedISO: '2026-07-24',
    dateModifiedISO: '2026-07-24',
    metaTitle: 'Best Flooring for Rental Properties (2026 Guide)',
    metaDescription: 'Best flooring for rental properties compared by cost, turn time, and lifespan: rigid-core LVP, laminate, carpet for bedrooms, and VCT for common areas. A guide for landlords and property managers.',
    relatedServices: ['vinyl-flooring-san-diego', 'laminate-flooring-san-diego', 'carpet-flooring-san-diego'],
    image: '/img/projects/portfolio/zelo-project-15.webp',
  },
  {
    slug: 'hardwood-floor-water-damage',
    title: 'Hardwood Floor Water Damage, Can It Be Saved?',
    excerpt: 'A water-damaged hardwood floor can often be saved if you catch it within 24 to 48 hours, extract the water, and dry the boards in place. Cupping is usually reversible; buckled boards almost always need replacing.',
    publishedDate: 'July 25, 2026',
    updatedDate: 'July 25, 2026',
    datePublishedISO: '2026-07-25',
    dateModifiedISO: '2026-07-25',
    metaTitle: 'Hardwood Floor Water Damage, Can It Be Saved?',
    metaDescription: 'Hardwood floor water damage explained: how to tell cupping from buckling, when drying works vs replacement, mold risk, insurance documentation, and repair costs by scope of damage.',
    relatedServices: ['hardwood-flooring-san-diego', 'vinyl-flooring-san-diego', 'laminate-flooring-san-diego'],
    image: '/img/hardwood-solid-wood-2.webp',
  },
  {
    slug: 'how-much-does-hardwood-flooring-cost',
    title: 'How Much Does Hardwood Flooring Cost',
    excerpt: 'Hardwood flooring costs $8 to $20 per square foot installed in 2026. Engineered runs $6 to $18 per square foot, solid runs $8 to $20, and a 1,500 square foot whole-home project typically lands $12,750 to $27,000.',
    publishedDate: 'July 26, 2026',
    updatedDate: 'July 26, 2026',
    datePublishedISO: '2026-07-26',
    dateModifiedISO: '2026-07-26',
    metaTitle: 'How Much Does Hardwood Flooring Cost in 2026',
    metaDescription: 'How much does hardwood flooring cost in 2026? $8-$20 per square foot installed. Cost by species, solid vs engineered, by room, and when refinishing beats full replacement.',
    relatedServices: ['hardwood-flooring-san-diego', 'laminate-flooring-san-diego', 'vinyl-flooring-san-diego'],
    image: '/img/hardwood-engineered-oak-2.webp',
  },
  {
    slug: 'how-much-does-laminate-flooring-cost',
    title: 'How Much Does Laminate Flooring Cost',
    excerpt: 'Laminate flooring costs $2.50 to $8.00 per square foot installed in 2026. Cost by AC wear rating, thickness, waterproof vs standard laminate, and real room-by-room totals for San Diego homes.',
    publishedDate: 'July 27, 2026',
    updatedDate: 'July 27, 2026',
    datePublishedISO: '2026-07-27',
    dateModifiedISO: '2026-07-27',
    metaTitle: 'How Much Does Laminate Flooring Cost in 2026',
    metaDescription: 'How much does laminate flooring cost in 2026? $2.50-$8.00 per square foot installed. Cost by AC rating, thickness, waterproof laminate, and labor by room.',
    relatedServices: ['laminate-flooring-san-diego', 'tile-flooring-san-diego', 'vinyl-flooring-san-diego'],
    image: '/img/laminate-flooring-ac5.jpg',
  },
  {
    slug: 'how-much-does-tile-flooring-cost',
    title: 'How Much Does Tile Flooring Cost',
    excerpt: 'Tile flooring costs $4 to $25 per square foot installed in 2026, driven mostly by tile type. Ceramic runs $4 to $8, porcelain $6 to $14, and natural stone $10 to $25 per square foot.',
    publishedDate: 'July 28, 2026',
    updatedDate: 'July 28, 2026',
    datePublishedISO: '2026-07-28',
    dateModifiedISO: '2026-07-28',
    metaTitle: 'How Much Does Tile Flooring Cost in 2026',
    metaDescription: 'How much does tile flooring cost in 2026? $4-$25 per square foot installed. Ceramic vs porcelain vs natural stone pricing, substrate prep costs, and cost by room.',
    relatedServices: ['tile-flooring-san-diego', 'vinyl-flooring-san-diego'],
    image: '/img/Ceramic-Tile.avif',
  },
  {
    slug: 'how-to-clean-and-reseal-grout-lines',
    title: 'How to Clean and Reseal Grout Lines',
    excerpt: 'Clean grout lines by scrubbing with a pH-neutral cleaner or baking soda paste, then reseal with a penetrating sealer every 12 to 18 months for floors. A step-by-step guide to sanded vs unsanded grout care.',
    publishedDate: 'July 29, 2026',
    updatedDate: 'July 29, 2026',
    datePublishedISO: '2026-07-29',
    dateModifiedISO: '2026-07-29',
    metaTitle: 'How to Clean and Reseal Grout Lines',
    metaDescription: 'How to clean and reseal grout lines: sanded vs unsanded grout, the right cleaners to use and avoid, resealing frequency, and signs your grout needs replacing instead of cleaning.',
    relatedServices: ['tile-flooring-san-diego', 'vinyl-flooring-san-diego'],
    image: '/img/projects/portfolio/zelo-project-17.webp',
  },
  {
    slug: 'how-to-clean-hardwood-floors',
    title: 'How to Clean Hardwood Floors the Right Way',
    excerpt: 'Most hardwood floors get ruined slowly by the wrong cleaner, not a single spill. Here is the daily, weekly, and deep-cleaning routine that protects the finish, plus whether Pine-Sol is actually safe to use.',
    publishedDate: 'July 30, 2026',
    updatedDate: 'July 30, 2026',
    datePublishedISO: '2026-07-30',
    dateModifiedISO: '2026-07-30',
    metaTitle: 'How to Clean Hardwood Floors the Right Way',
    metaDescription: 'How to clean hardwood floors without damaging the finish: the right cleaners, why Pine-Sol and vinegar are not recommended, and a deep-cleaning routine for polyurethane and oil finishes.',
    relatedServices: ['hardwood-flooring-san-diego', 'vinyl-flooring-san-diego', 'tile-flooring-san-diego'],
    image: '/img/hardwood-solid-wood.webp',
  },
  {
    slug: 'how-to-clean-laminate-wood-floors',
    title: 'How to Clean Laminate Wood Floors',
    excerpt: 'Sweep laminate every few days, then damp mop weekly with a barely-damp microfiber mop and a pH-neutral cleaner. Never wet-mop or steam mop, since laminate\'s wood-fiber core swells once moisture gets past the surface.',
    publishedDate: 'July 31, 2026',
    updatedDate: 'July 31, 2026',
    datePublishedISO: '2026-07-31',
    dateModifiedISO: '2026-07-31',
    metaTitle: 'How to Clean Laminate Wood Floors',
    metaDescription: 'How to clean laminate wood floors correctly: the right sweeping and damp-mopping routine, what to avoid, spill response, and stain removal without damaging the wear layer.',
    relatedServices: ['laminate-flooring-san-diego', 'vinyl-flooring-san-diego', 'hardwood-flooring-san-diego'],
    image: '/img/Wide-Plank-Laminate-Flooring.jpg',
  },
  {
    slug: 'how-to-fix-a-sagging-or-squeaky-hardwood-floor',
    title: 'How to Fix a Sagging or Squeaky Hardwood Floor',
    excerpt: 'A squeak is usually a loose subfloor connection, fixed in an afternoon. A sag means a joist, subfloor panel, or foundation support has failed underneath, and it needs structural repair before any refinishing.',
    publishedDate: 'August 1, 2026',
    updatedDate: 'August 1, 2026',
    datePublishedISO: '2026-08-01',
    dateModifiedISO: '2026-08-01',
    metaTitle: 'How to Fix a Sagging or Squeaky Hardwood Floor',
    metaDescription: 'How to fix a sagging or squeaky hardwood floor: what causes each problem, how to tell a surface fix from a structural repair, and real costs for joist sistering and subfloor work.',
    relatedServices: ['hardwood-flooring-san-diego', 'vinyl-flooring-san-diego'],
    image: '/img/engineered-oak-flooring-2.jpg',
  },
  {
    slug: 'how-to-fix-scratches-and-dents-in-vinyl-plank',
    title: 'How to Fix Scratches and Dents in Vinyl Plank',
    excerpt: 'Vinyl plank resists scratches well but is not scratch-proof. Light scratches buff out with a color-matched repair kit in about 15 minutes, and deeper gouges usually mean swapping one plank, not the whole floor.',
    publishedDate: 'August 2, 2026',
    updatedDate: 'August 2, 2026',
    datePublishedISO: '2026-08-02',
    dateModifiedISO: '2026-08-02',
    metaTitle: 'How to Fix Scratches and Dents in Vinyl Plank',
    metaDescription: 'How to fix scratches and dents in vinyl plank flooring: repair kits for light scratches, heat fixes for shallow dents, and how to replace a single click-lock or glue-down plank.',
    relatedServices: ['vinyl-flooring-san-diego', 'laminate-flooring-san-diego', 'hardwood-flooring-san-diego'],
    image: '/img/Rigid-Core-Vinyl.jpg',
  },
  {
    slug: 'how-to-remove-carpet-stains',
    title: 'How to Remove Carpet Stains, Room by Room',
    excerpt: 'Most carpet stains are lost in the first 10 minutes, not the first wash. Blot instead of rub, match the cleaner to the stain, and treat it fast to lift wine, pet accidents, grease, and ink without professional extraction.',
    publishedDate: 'August 3, 2026',
    updatedDate: 'August 3, 2026',
    datePublishedISO: '2026-08-03',
    dateModifiedISO: '2026-08-03',
    metaTitle: 'How to Remove Carpet Stains, Room by Room',
    metaDescription: 'How to remove carpet stains room by room: wine, coffee, grease, pet urine, blood, and ink, plus why nylon and polyester carpet react differently to the same spill.',
    relatedServices: ['carpet-flooring-san-diego', 'vinyl-flooring-san-diego'],
    image: '/img/carpet-installed-bedroom-2.webp',
  },
  {
    slug: 'is-cork-flooring-good-for-kitchens',
    title: 'Is Cork Flooring Good for Kitchens?',
    excerpt: 'Yes, cork flooring works well in a kitchen with the right format and sealing. Glue-down cork tile with a polyurethane finish and a sealed perimeter at the sink, dishwasher, and fridge holds up for 15 to 25 years.',
    publishedDate: 'August 4, 2026',
    updatedDate: 'August 4, 2026',
    datePublishedISO: '2026-08-04',
    dateModifiedISO: '2026-08-04',
    metaTitle: 'Is Cork Flooring Good for Kitchens?',
    metaDescription: 'Is cork flooring good for kitchens? Yes, with glue-down tile and proper sealing. How to seal splash zones, cork vs floating plank, and real cost and installation timeline.',
    relatedServices: ['cork-flooring-san-diego', 'tile-flooring-san-diego', 'vinyl-flooring-san-diego'],
    image: '/img/Cork-Tile-Flooring.webp',
  },
  {
    slug: 'is-laminate-flooring-waterproof',
    title: 'Is Laminate Flooring Actually Waterproof?',
    excerpt: 'No, most laminate flooring is water resistant, not waterproof, and its wood-fiber core swells if water sits for more than a few hours. Waterproof laminate lines close the gap, but even those have real limits.',
    publishedDate: 'August 5, 2026',
    updatedDate: 'August 5, 2026',
    datePublishedISO: '2026-08-05',
    dateModifiedISO: '2026-08-05',
    metaTitle: 'Is Laminate Flooring Actually Waterproof?',
    metaDescription: 'Is laminate flooring waterproof? Water resistant vs waterproof laminate explained, which lines like Pergo Outlast+ hold up best, and where tile or LVP is still the safer choice.',
    relatedServices: ['laminate-flooring-san-diego', 'vinyl-flooring-san-diego', 'tile-flooring-san-diego'],
    image: '/img/Water-Resistant-Laminate-Flooring.jpg',
  },
  {
    slug: 'is-vinyl-plank-flooring-good-for-basements',
    title: 'Is Vinyl Plank Flooring Good for Basements?',
    excerpt: 'Yes, rigid-core vinyl plank is one of the few materials installed below grade with confidence. It is 100 percent waterproof at the surface, but it still needs a vapor barrier over the concrete slab.',
    publishedDate: 'August 6, 2026',
    updatedDate: 'August 6, 2026',
    datePublishedISO: '2026-08-06',
    dateModifiedISO: '2026-08-06',
    metaTitle: 'Is Vinyl Plank Flooring Good for Basements?',
    metaDescription: 'Is vinyl plank flooring good for basements? Yes, with a vapor barrier. Moisture testing, floating vs glue-down installation, and how to solve the cold-floor feel below grade.',
    relatedServices: ['vinyl-flooring-san-diego', 'laminate-flooring-san-diego', 'tile-flooring-san-diego'],
    image: '/img/projects/portfolio/zelo-project-19.webp',
  },
  {
    slug: 'janka-hardness-chart-for-hardwood-flooring',
    title: 'Janka Hardness Chart for Hardwood Flooring',
    excerpt: 'The Janka hardness scale ranks wood species by how much force it takes to dent the surface. Brazilian walnut tops the chart at 3,680 lbf, hickory leads domestic species, and white oak balances hardness and cost.',
    publishedDate: 'August 7, 2026',
    updatedDate: 'August 7, 2026',
    datePublishedISO: '2026-08-07',
    dateModifiedISO: '2026-08-07',
    metaTitle: 'Janka Hardness Chart for Hardwood Flooring',
    metaDescription: 'Janka hardness chart for hardwood flooring species, from Brazilian walnut to pine. What the rating actually predicts, and how to choose a species for pets, kids, and high-traffic homes.',
    relatedServices: ['hardwood-flooring-san-diego', 'vinyl-flooring-san-diego', 'laminate-flooring-san-diego'],
    image: '/img/engineered-oak-flooring-3.jpg',
  },
  {
    slug: 'lvp-vs-lvt-flooring',
    title: 'LVP vs LVT Flooring, What Is the Difference?',
    excerpt: 'LVP and LVT share the same vinyl core, the only difference is the shape. LVP is milled into planks that mimic hardwood; LVT is milled into tiles that mimic ceramic or stone, often with a grout-line option.',
    publishedDate: 'August 8, 2026',
    updatedDate: 'August 8, 2026',
    datePublishedISO: '2026-08-08',
    dateModifiedISO: '2026-08-08',
    metaTitle: 'LVP vs LVT Flooring, What Is the Difference?',
    metaDescription: 'LVP vs LVT flooring compared: plank vs tile format, grout-line options for LVT, installation patterns, and cost differences between the two luxury vinyl formats.',
    relatedServices: ['vinyl-flooring-san-diego', 'tile-flooring-san-diego'],
    image: '/img/projects/portfolio/zelo-project-21.webp',
  },
  {
    slug: 'porcelain-vs-ceramic-tile',
    title: 'Porcelain vs Ceramic Tile, What Is the Difference?',
    excerpt: 'Porcelain tile absorbs less than 0.5 percent water and is dense enough for showers and outdoor use. Ceramic absorbs more, costs 20 to 30 percent less, and works well on walls and low-traffic floors.',
    publishedDate: 'August 9, 2026',
    updatedDate: 'August 9, 2026',
    datePublishedISO: '2026-08-09',
    dateModifiedISO: '2026-08-09',
    metaTitle: 'Porcelain vs Ceramic Tile, What Is the Difference?',
    metaDescription: 'Porcelain vs ceramic tile compared: water absorption, durability, cost, and where each one belongs, from shower floors to guest bathroom walls.',
    relatedServices: ['tile-flooring-san-diego', 'vinyl-flooring-san-diego'],
    image: '/img/projects/portfolio/zelo-project-22.webp',
  },
  {
    slug: 'prefinished-vs-site-finished-hardwood',
    title: 'Prefinished vs Site-Finished Hardwood, Which Is Better?',
    excerpt: 'Prefinished hardwood is factory-cured and installs faster with no dust. Site-finished hardwood is sanded and coated in place for a perfectly flat, seamless surface that can match an existing floor\'s exact color.',
    publishedDate: 'August 10, 2026',
    updatedDate: 'August 10, 2026',
    datePublishedISO: '2026-08-10',
    dateModifiedISO: '2026-08-10',
    metaTitle: 'Prefinished vs Site-Finished Hardwood, Which Is Better?',
    metaDescription: 'Prefinished vs site-finished hardwood compared: durability, timeline, cost, and which one to choose for a whole-home install versus matching an existing floor.',
    relatedServices: ['hardwood-flooring-san-diego', 'vinyl-flooring-san-diego'],
    image: '/img/hardwood-engineered-oak-3.webp',
  },
  {
    slug: 'rigid-core-vs-wpc-vinyl-plank',
    title: 'Rigid Core vs WPC Vinyl Plank, Which Should You Choose?',
    excerpt: 'Rigid core vinyl plank splits into two core types, SPC and WPC. SPC is denser and more stable over a concrete slab; WPC feels warmer and quieter underfoot, better suited to bedrooms and upper floors.',
    publishedDate: 'August 11, 2026',
    updatedDate: 'August 11, 2026',
    datePublishedISO: '2026-08-11',
    dateModifiedISO: '2026-08-11',
    metaTitle: 'Rigid Core vs WPC Vinyl Plank, Which Should You Choose?',
    metaDescription: 'Rigid core vs WPC vinyl plank compared: SPC and WPC core construction, stability over a concrete slab, comfort underfoot, and which core fits which room.',
    relatedServices: ['vinyl-flooring-san-diego', 'tile-flooring-san-diego', 'hardwood-flooring-san-diego'],
    image: '/img/projects/portfolio/zelo-project-24.webp',
  },
  {
    slug: 'rubber-flooring-for-a-home-gym',
    title: 'Best Rubber Flooring for a Home Gym',
    excerpt: 'The best rubber flooring for a home gym is matched to activity, 3/8 inch for cardio, 1/2 inch for free weights, and 3/4 inch to 1 inch for olympic lifting and dropped barbells. A thickness and cost guide.',
    publishedDate: 'August 12, 2026',
    updatedDate: 'August 12, 2026',
    datePublishedISO: '2026-08-12',
    dateModifiedISO: '2026-08-12',
    metaTitle: 'Best Rubber Flooring for a Home Gym',
    metaDescription: 'Best rubber flooring for a home gym by activity and thickness. Rolled vs interlocking tile, the smell question, slab prep, and installed cost for a garage gym floor.',
    relatedServices: ['rubber-flooring-san-diego', 'vinyl-flooring-san-diego'],
    image: '/img/rubber-rolls-converted.webp',
  },
  {
    slug: 'rubber-flooring-for-garages',
    title: 'Rubber Flooring for Garages, Pros, Cons, and Cost',
    excerpt: 'Rubber flooring hides slab cracks and oil stains without a re-pour, resists dropped tools, and holds up under vehicle weight. A guide to tile vs rolled rubber, and how the cost compares to epoxy coating.',
    publishedDate: 'August 13, 2026',
    updatedDate: 'August 13, 2026',
    datePublishedISO: '2026-08-13',
    dateModifiedISO: '2026-08-13',
    metaTitle: 'Rubber Flooring for Garages, Pros, Cons, and Cost',
    metaDescription: 'Rubber flooring for garages: hides cracks and oil stains, holds up under a parked car, and costs $3.50 to $7.50 per square foot installed. Compared against epoxy coating.',
    relatedServices: ['rubber-flooring-san-diego', 'vinyl-composition-tile-flooring-san-diego'],
    image: '/img/Rubber-Tiles.jpg',
  },
  {
    slug: 'vct-maintenance-stripping-and-waxing',
    title: 'VCT Maintenance, Stripping and Waxing Explained',
    excerpt: 'VCT does not come out of the box protected. It needs an applied acrylic finish, and a full strip-and-rewax every 12 to 24 months depending on traffic, or the finish wears through and the tile stains permanently.',
    publishedDate: 'August 14, 2026',
    updatedDate: 'August 14, 2026',
    datePublishedISO: '2026-08-14',
    dateModifiedISO: '2026-08-14',
    metaTitle: 'VCT Maintenance, Stripping and Waxing Explained',
    metaDescription: 'VCT maintenance, stripping, and waxing explained: finish coat cycles, burnishing vs a full strip, how often by traffic level, and the real cost of skipping the schedule.',
    relatedServices: ['vinyl-composition-tile-flooring-san-diego', 'rubber-flooring-san-diego'],
    image: '/img/ARM-VCT-color__26247.jpg',
  },
  {
    slug: 'vct-vs-lvt-flooring',
    title: 'VCT vs LVT Flooring, What Is the Difference?',
    excerpt: 'VCT is a solid tile that needs an applied finish and regular stripping and waxing. LVT is a layered vinyl tile with a factory wear layer that never needs wax. A cost and maintenance comparison for commercial spaces.',
    publishedDate: 'August 15, 2026',
    updatedDate: 'August 15, 2026',
    datePublishedISO: '2026-08-15',
    dateModifiedISO: '2026-08-15',
    metaTitle: 'VCT vs LVT Flooring, What Is the Difference?',
    metaDescription: 'VCT vs LVT flooring compared: construction, cost, and maintenance. Why VCT needs stripping and waxing and LVT does not, and which commercial spaces favor each.',
    relatedServices: ['vinyl-composition-tile-flooring-san-diego', 'vinyl-flooring-san-diego'],
    image: '/img/Vinyl-Composition-Tile-VCT-4.jpg',
  },
  {
    slug: 'what-is-cork-flooring',
    title: 'What Is Cork Flooring? Pros, Cons, and Cost',
    excerpt: 'Cork flooring is made from the bark of the cork oak tree, harvested every 9 years without cutting down the tree. It is soft, warm, naturally antimicrobial, and reduces impact noise by 15 to 20 decibels.',
    publishedDate: 'August 16, 2026',
    updatedDate: 'August 16, 2026',
    datePublishedISO: '2026-08-16',
    dateModifiedISO: '2026-08-16',
    metaTitle: 'What Is Cork Flooring? Pros, Cons, and Cost',
    metaDescription: 'What is cork flooring? How it is made, pros and cons, where it works best in a home, glue-down tile vs floating plank, and installed cost per square foot.',
    relatedServices: ['cork-flooring-san-diego', 'hardwood-flooring-san-diego', 'laminate-flooring-san-diego'],
    image: '/img/Cork-Plank-Flooring.webp',
  },
  {
    slug: 'what-is-vct-flooring',
    title: 'What Is VCT (Vinyl Composition Tile) Flooring?',
    excerpt: 'VCT is a resilient floor tile built mostly from ground limestone bound with vinyl resin, plasticizer, and pigment. It costs $2 to $5 per square foot installed and is the standard floor in schools and hospitals.',
    publishedDate: 'August 17, 2026',
    updatedDate: 'August 17, 2026',
    datePublishedISO: '2026-08-17',
    dateModifiedISO: '2026-08-17',
    metaTitle: 'What Is VCT (Vinyl Composition Tile) Flooring?',
    metaDescription: 'What is VCT flooring? What it is made of, why schools and hospitals use it, the strip-and-wax maintenance cycle, asbestos concerns in old tile, and installed cost.',
    relatedServices: ['vinyl-composition-tile-flooring-san-diego', 'rubber-flooring-san-diego', 'tile-flooring-san-diego'],
    image: '/img/Vinyl-Composition-Tile-VCT-3.jpg',
  },
  {
    slug: 'rubber-flooring-for-commercial-gyms',
    title: 'Rubber Flooring for Commercial Gyms, Cost and Install Process',
    excerpt: 'Commercial gym rubber flooring by zone, heat-welded seams vs tile, product brands compared (Ecore, Mondo, Regupol), buildout cost per square foot, and scheduling around an operating gym.',
    publishedDate: 'August 18, 2026',
    updatedDate: 'August 18, 2026',
    datePublishedISO: '2026-08-18',
    dateModifiedISO: '2026-08-18',
    metaTitle: 'Rubber Flooring for Commercial Gyms, Cost and Install Process',
    metaDescription: 'Commercial gym rubber flooring by zone, heat-welded seams vs tile, brand comparison, cost per square foot, and after-hours scheduling for an operating gym.',
    relatedServices: ['rubber-flooring-san-diego', 'vinyl-composition-tile-flooring-san-diego'],
    image: '/img/rubber-tiles-commercial.webp',
  },
  {
    slug: 'daycare-flooring-requirements-and-play-area-safety',
    title: 'Daycare Flooring Requirements and Play Area Safety',
    excerpt: 'ASTM F1292 fall-attenuation basics, matching rubber thickness to play equipment fall height, poured EPDM vs rubber tile, cleaning and disinfecting, and California licensing considerations.',
    publishedDate: 'August 19, 2026',
    updatedDate: 'August 19, 2026',
    datePublishedISO: '2026-08-19',
    dateModifiedISO: '2026-08-19',
    metaTitle: 'Daycare Flooring Requirements and Play Area Safety',
    metaDescription: 'Daycare flooring requirements explained: ASTM F1292 fall-height matching, poured EPDM vs rubber tile, cleaning, California licensing, and cost per square foot.',
    relatedServices: ['rubber-flooring-san-diego', 'tile-flooring-san-diego'],
    image: '/img/rubber-mosaic-pattern.webp',
  },
  {
    slug: 'rubber-flooring-vs-vct-for-commercial-spaces',
    title: 'Rubber Flooring vs VCT for Commercial Spaces',
    excerpt: 'Rubber vs VCT compared for commercial use: construction, impact absorption and slip resistance, strip-and-wax vs sweep-and-mop maintenance, cost over time, and which rooms favor each.',
    publishedDate: 'August 20, 2026',
    updatedDate: 'August 20, 2026',
    datePublishedISO: '2026-08-20',
    dateModifiedISO: '2026-08-20',
    metaTitle: 'Rubber Flooring vs VCT for Commercial Spaces',
    metaDescription: 'Rubber vs VCT for commercial spaces compared: impact absorption, slip resistance, maintenance, and cost over time. Which one fits which room.',
    relatedServices: ['rubber-flooring-san-diego', 'vinyl-composition-tile-flooring-san-diego'],
    image: '/img/9191-Ecofit-Rubber-Floor_Mosaic.jpg',
  },
  {
    slug: 'how-much-does-rubber-flooring-cost',
    title: 'How Much Does Rubber Flooring Cost',
    excerpt: 'Rubber flooring costs $3.50 to $16 per square foot installed, driven mostly by thickness and use case. Home gym and garage rubber runs $3.50 to $10; commercial and daycare surfacing runs $6 to $16.',
    publishedDate: 'August 21, 2026',
    updatedDate: 'August 21, 2026',
    datePublishedISO: '2026-08-21',
    dateModifiedISO: '2026-08-21',
    metaTitle: 'How Much Does Rubber Flooring Cost',
    metaDescription: 'How much does rubber flooring cost? Pricing by thickness, format, and use case, home gym, garage, commercial gym, and daycare, plus what affects your total price.',
    relatedServices: ['rubber-flooring-san-diego'],
    image: '/img/rubber-rolls-converted.webp',
  },
  {
    slug: 'what-is-rubber-flooring',
    title: 'What Is Rubber Flooring? Pros, Cons, and Cost',
    excerpt: 'Rubber flooring is made from recycled SBR tire rubber or virgin EPDM, sold as rolled sheet, tile, or poured surfacing. It costs $3.50 to $16 per square foot and absorbs impact no other flooring material does.',
    publishedDate: 'August 22, 2026',
    updatedDate: 'August 22, 2026',
    datePublishedISO: '2026-08-22',
    dateModifiedISO: '2026-08-22',
    metaTitle: 'What Is Rubber Flooring? Pros, Cons, and Cost',
    metaDescription: 'What is rubber flooring? SBR vs EPDM, rolled vs tile vs poured formats, pros and cons, where it fits in a home or commercial space, and installed cost.',
    relatedServices: ['rubber-flooring-san-diego'],
    image: '/img/rubber-tiles-commercial.webp',
  },
  {
    slug: 'rubber-flooring-maintenance-and-cleaning',
    title: 'Rubber Flooring Maintenance and Cleaning',
    excerpt: 'How to clean and maintain rubber flooring: the right cleaners, what to avoid, fixing a lifted seam or tile, slowing sun fade, and how residential and commercial cleaning schedules differ.',
    publishedDate: 'August 23, 2026',
    updatedDate: 'August 23, 2026',
    datePublishedISO: '2026-08-23',
    dateModifiedISO: '2026-08-23',
    metaTitle: 'Rubber Flooring Maintenance and Cleaning',
    metaDescription: 'Rubber flooring maintenance and cleaning explained: the right cleaners, what to avoid, seam repair, sun fade, and residential vs commercial schedules.',
    relatedServices: ['rubber-flooring-san-diego'],
    image: '/img/Rubber-Tiles.jpg',
  },
];

export const PUBLISHED_BLOG_SLUGS = [
  'lvp-vs-engineered-hardwood',
  'types-of-hardwood-flooring',
  'low-pile-vs-high-pile-carpet',
  'how-to-clean-luxury-vinyl-plank-flooring',
  'tile-vs-vinyl-flooring',
  'vinyl-vs-laminate-flooring',
  'how-to-install-vinyl-plank-flooring',
  'best-flooring-for-san-diego-homes',
  'how-long-does-hardwood-refinishing-take',
  'laminate-flooring-thickness',
  'laminate-over-existing-floors',
  'cost-to-install-carpet',
  'best-carpet-for-living-room',
  'lvp-vs-hardwood',
  'best-flooring-for-pets',
  'vinyl-plank-flooring-cost',
  'polyester-vs-nylon-carpet',
  'engineered-vs-solid-hardwood',
  'flooring-services-guide',
  'how-to-choose-a-flooring-company',
  'is-free-flooring-installation-real',
  'wall-to-wall-carpet',
  'flooring-design-ideas-by-room',
  'wood-look-tile-vs-hardwood',
  'bathroom-flooring-installation',
  'best-flooring-for-new-construction',
  'best-flooring-for-schools',
  'best-flooring-for-craft-room',
  'bathroom-floor-tile-ideas',
  'best-tile-for-outdoor-patios-and-pools',
  'can-laminate-flooring-be-repaired',
  'carpet-padding-guide',
  'cork-flooring-maintenance-and-cleaning',
  'flooring-for-rental-properties',
  'hardwood-floor-water-damage',
  'how-much-does-hardwood-flooring-cost',
  'how-much-does-laminate-flooring-cost',
  'how-much-does-tile-flooring-cost',
  'how-to-clean-and-reseal-grout-lines',
  'how-to-clean-hardwood-floors',
  'how-to-clean-laminate-wood-floors',
  'how-to-fix-a-sagging-or-squeaky-hardwood-floor',
  'how-to-fix-scratches-and-dents-in-vinyl-plank',
  'how-to-remove-carpet-stains',
  'is-cork-flooring-good-for-kitchens',
  'is-laminate-flooring-waterproof',
  'is-vinyl-plank-flooring-good-for-basements',
  'janka-hardness-chart-for-hardwood-flooring',
  'lvp-vs-lvt-flooring',
  'porcelain-vs-ceramic-tile',
  'prefinished-vs-site-finished-hardwood',
  'rigid-core-vs-wpc-vinyl-plank',
  'rubber-flooring-for-a-home-gym',
  'rubber-flooring-for-garages',
  'vct-maintenance-stripping-and-waxing',
  'vct-vs-lvt-flooring',
  'what-is-cork-flooring',
  'what-is-vct-flooring',
  'rubber-flooring-for-commercial-gyms',
  'daycare-flooring-requirements-and-play-area-safety',
  'rubber-flooring-vs-vct-for-commercial-spaces',
  'how-much-does-rubber-flooring-cost',
  'what-is-rubber-flooring',
  'rubber-flooring-maintenance-and-cleaning',
];

// Build-time "today" (YYYY-MM-DD). Frozen when `next build` runs, NOT at request time.
// This is what makes scheduling work: a post listed in PUBLISHED_BLOG_SLUGS but dated in
// the future stays hidden until a build runs on or after its datePublishedISO. Pair this
// with a nightly Hostinger cron rebuild (see SCHEDULING.md) so future-dated posts go live
// on their own without a manual re-deploy.
const BUILD_TODAY = new Date().toISOString().slice(0, 10);

// A post is live when it is (1) switched on via the slug list AND (2) its publish date has
// arrived as of the build. Lexicographic compare is safe for fixed-width YYYY-MM-DD strings.
export const isBlogPostLive = (p: BlogPost, asOf: string = BUILD_TODAY) =>
  PUBLISHED_BLOG_SLUGS.includes(p.slug) && p.datePublishedISO.slice(0, 10) <= asOf;

export const PUBLISHED_BLOG_POSTS = BLOG_POSTS.filter((p) => isBlogPostLive(p)).sort((a, b) =>
  b.datePublishedISO.localeCompare(a.datePublishedISO)
);

export const getBlogPost = (slug: string) => BLOG_POSTS.find((p) => p.slug === slug);
